### ISSUE TITLE
Possibility to extend topic submission deadline?

### ISSUE THREAD

**Issue by wmclaxton** [WebOfTrustInfo/rwot9-prague#4]
I am planning to attend RWOT Prague and at the moment am working on a paper (https://docs.google.com/document/d/1xzcuhc_pt-TKIBb6WIYZsMe5hDM41kSmstkCKOVFTC8/edit?usp=sharing).  My collaborator Wai Chong and I would like to request a few days more time to pull this paper together.

**Comment by jandrieu** [comment]
You still have a few weeks. Ping me by email if that's not enough.

**Comment by wmclaxton** [comment]
We have submitted our topic submission.  Refer to PR #17 (https://github.com/WebOfTrustInfo/rwot9-prague/pull/17).
