### ISSUE TITLE
Advanced reading submission 

### ISSUE THREAD

**Issue by SSI-Ambassador** [WebOfTrustInfo/rwot9-prague#64]
I still have to find my way into Github and therefore would like to submit it as issue instead of a pull request. 

_Listing for README:_
Topic: Verifiable Credentials Use Cases
Name: Using verifiable credentials for German government grants. 
Description: 
- This paper describes the potential usage of the SSI framework for the application of government grants. It takes into consideration the current developments from the German government with their "Bundes-chain" initiative. 
- By Adrian Doerk
- #verifiable-credentials #ssi #government  

_Paper submission_

**Using verifiable credentials for German government grants.**
By Adrian Doerk
Contact: contact@hodlhelper.com

**Abstract:**

This paper aims to provide an overview how verified credentials could be implemented to facilitate the application process for German government grants for students. These grants are defined in the BAföG (BundesAusbildungsFörderungsGesetz – &quot;Federal law for the promotion of training&quot;) and every student needs to reapply once or twice a year.

**The status quo:**

In order to obtain government grants a student must download, fill, print, sign, and sent a lot of documents. While online uploads are getting more accepted, the problem of repetitive uploads and third-party confirmation request, such as bank or university acknowledgements remain.

While § 46 Abs. 1. BAföG refers to §36a SGB I in regards of the identification via eID and DE-Mail, further integrations like ELSTER (currently used for tax transmissions) are under examination. However, these are rather silo solutions, which operate in a closed environment.

**A use case for verifiable credentials**

In order to obtain the government grant, every student is required to prove the following:
(Certificate, issued by), (non-exhaustive list)

Current account holdings, Bank
Certification of enrolment, University
Certification of insurance, Insurance company.

Currently the student is required to obtain all these certificates and send them (digitally or analogue) to a local administration. This is not only cumbersome, but also leaves room for errors and fraud.

**Based on the &quot;Bundes-chain&quot; – a blockchain/DLT solution run by the German government.**

As noted in the blockchain position paper from June 2019 Germany aims to build an alternative to the existing identity options based on a government-owned blockchain infrastructure.

Source: [Blockchain position paper of CDU/CSU Germany (PDF).](https://www.cducsu.de/sites/default/files/2019-06/Positionspapier%20Blockchain%20Papier\_Neu\_0.pdf)

&quot;The state shall determine notaries and issue them an acknowledged identity. These notaries then can confirm identities and issue digital identification certificates to multiple stakeholders such as individuals, companies, or machines. Infrastructure for this identification system can be the so-called &quot;Bundes-chain&quot; (government-chain), which is an interoperable blockchain infrastructure run by the German government.&quot; 
Source: [German parliamentary party calls for governmental blockchain infrastructure for identity management - Adrian Doerk on LinkedIn.](https://www.linkedin.com/pulse/german-parliamentary-party-calls-governmental-blockchain-adrian-doerk/)

Once stakeholders like universities, financial institutions and insurance companies are registered on the Bundes-chain, they can issue verified credentials to the identity holder.

**Goal:**

This paper aims to start a discussion on how to approach SSI solutions for administrative processes. While this paper addresses a specific use case for one German application process, the solution should be interoperable across government domains and take international standards in consideration.

Further discussions are necessary:
Scope of implementation, Important stakeholders, Integration with existing solutions, Identify pain points and technology challenges,

**Comment by ChristopherA** [comment]
@shannona, could you assist @Doerkx with this topic submission. Thanks!

**Comment by shannona** [comment]
Paper is uploaded (https://github.com/WebOfTrustInfo/rwot9-prague/blob/master/topics-and-advance-readings/vcs-for-german-grants.md) and added to README.
