### ISSUE TITLE
Seedquest 3D Game Mnemonic for cryptographic key learning and recovery

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrustInfo/rwot9-prague#80]
### Name of Demo
Seedquest 3D Mnemonic for Key Recovery
### Demo Details (for titling)
Demonstrate 3D Game application for learning and then recovering cryptographic strength seeds for cryptographic keys. Demo'd a very early version of this game at RWOT7. It is not much more mature and nearing release quality. This is an open source Apache2 licensed code.
### Name(s) of speakers
Samuel Smith
### Contact (phone & email)
801 592 8230  sam@samuelsmith.org
### Name of Company/Project
ConsenSys SeedQuest
### Content (upload an outline or ppt or something to let us have some sense of what we need).

https://github.com/reputage/seedQuest

**Comment by dmitrizagidulin** [comment]
Fantastic, thank you so much @SmithSamuelM!
