### ISSUE TITLE
Datashards

### ISSUE THREAD

**Issue by cwebber** [WebOfTrustInfo/rwot9-prague#91]
### Name of Demo
Datashards

### Demo Details (for titling)
Demonstration of Datashards clients, in action.

### Name(s) of speakers
Christopher Lemmer Webber, maybe with Serge Wroclawski helping.

### Contact (phone & email)
+17736142279 & cwebber@dustycloud.org

### Name of Company/Project
Spritely

### Content (upload an outline or ppt or something to let us have some sense of what we need).
I'll need to be able to attach my laptop to hdmi output to show the demo live.
Alternately, I could just walk through a PDF, but seeing is believing ;)

**Comment by dmitrizagidulin** [comment]
Thanks @cwebber!
