### ISSUE TITLE
Using the Tamarin Prover for DIDComm protocols

### ISSUE THREAD

**Issue by SvenHammann90** [WebOfTrustInfo/rwot9-prague#92]
### Name of Demo
Using the Tamarin Prover for DIDComm Protocols

### Demo Details (for titling)
I show how to use the protocol verification tool Tamarin to model DIDComm protocols, in particular the exchange of peer DIDs. I show how I used Tamarin to uncover a potential issue, which led to a contribution to the peer DID spec.

### Name(s) of speakers
Sven Hammann

### Contact (phone & email)
sven.hammann@inf.ethz.ch
0041797263111

### Name of Company/Project
Information Security Group, ETH Zurich

### Content (upload an outline or ppt or something to let us have some sense of what we need).
I will share my screen and show Tamarin and the theories I mention in my advanced reading paper:
https://github.com/WebOfTrustInfo/rwot9-prague/blob/master/topics-and-advance-readings/formal_verification_for_ssi.md
. For people who wish to recreate the results:
- Tamarin is available here: https://tamarin-prover.github.io/
- I have uploaded my models here: https://github.com/SvenHammann90/SSI/tree/master/RWOT_9

**Comment by dmitrizagidulin** [comment]
Thanks @SvenHammann90 !
