### ISSUE TITLE
Passing credentials from one party to the next, to the next...

### ISSUE THREAD

**Issue by RieksJ** [WebOfTrustInfo/rwot9-prague#95]
### Demo Details (for titling)
The demo shows 
* how a Dutch citizen can go to the citizensdesk of a municipality to get a national ID credential from the (simulated) Citizens Registration Administration in an SSI app.
* how that citizen can then use it to register as a self-employed enterprise at the (simulated) Dutch Chamber of Commerce, and get a credential saying so in his SSI app 
* how that citizen can then use that credential to obtain a business bank-account at any of the (simulated) banks.

### Name(s) of speakers
Rieks Joosten

### Contact (phone & email)
rieks.joosten@tno.nl
+31622901317

### Name of Company/Project
TNO / SSI-Lab

### Content (upload an outline or ppt or something to let us have some sense of what we need).
See under ### Demo Details

**Comment by dmitrizagidulin** [comment]
Thanks @RieksJ !
