### ISSUE TITLE
SSI helps to fill in forms

### ISSUE THREAD

**Issue by RieksJ** [WebOfTrustInfo/rwot9-prague#96]
### Demo Details (for titling)
Electronic (business) transactions basically consist of users wanting a product or service, going to the website of a provider, filling in forms and uploading pdfs, the provider evaluating these forms, and deciding whether or not to provide the product or service.

The user may expericience difficulties, such as:
* not understanding what is being asked
* not knowing where to get the requested information
* physically go somewhere (e.g. a municipality, or a medical specialist) to get a paper with that data
* scanning and uploading paperwork
* feeling of anxiety, not knowing whether or not the data was good
* getting harassed by the provider because the provided data was not good
* it takes forever for the provider to decide
* giving up - it is all too difficult.

The provider may experience difficulties, such as:
* wrong data being provided by user (he didn't understand it, or just got it wrong)
* verifying the data against authoritative sources (manually, or semi-automatically)
* inability to get data himself (e.g. due to GDPR restrictions)
* cost and time incurred in validating data
* customer satisfaction is down because of the difficulty of the required data

This demonstration aims to motivate organizations to start experimenting with SSI technologies, by conveying to them that the more organizations will start to participate, the easier and cheaper electronic business transactions will become.

The demonstration itself is about a user that wants to obtain a subsidy from the Dutch province of Limburg, for a contribution in the maintenance costs of a monument in that province. 
So he goes to the website of the Province of Limburg (PL), where he is presented a complicated form, that can both be manually filled in, or (partly) with a credential from the Dutch Citizens Registration, and/or a credential from the Dutch Governmental body that deals with monuments. The demo shows that credentials can be used to fill in part of the form, thus making it easier to fill in forms
It also shows how the PL can decide about the subsidy, and how that decision results in (yet) another credential that the user can collect in his wallet.

### Name(s) of speakers
Rieks Joosten

### Contact (phone & email)
rieks.joosten@tno.nl
+31622901317

### Name of Company/Project
TNO / SSI-Lab / Techruption

### Content (upload an outline or ppt or something to let us have some sense of what we need).
See earlier

**Comment by dmitrizagidulin** [comment]
Very interesting, thanks!

**Comment by RieksJ** [comment]
@dmitrizagidulin: are the video's of the presentations already available somewhere?

**Comment by dmitrizagidulin** [comment]
@RieksJ I'm not sure. I'll double-check!
