### ISSUE TITLE
Utilizing zero-knowledge proofs and verifiable credentials to provide privacy-friendly income tests for social housing

### ISSUE THREAD

**Issue by dlamers** [WebOfTrustInfo/rwot9-prague#97]
### Name of Demo
Utilizing zero-knowledge proofs and verifiable credentials to provide privacy-friendly income tests for social housing

### Demo Details (for titling)
In this demo we make use of the universal ledger agent, verifiable credentials and zero-knowledge proofs to create a blockchain agnostic SSI solution focusing on privacy and data minimalisation for income tests

### Name(s) of speakers
David Lamers

### Contact (phone & email)
0031624650111 - david.lamers@rabobank.nl

### Name of Company/Project
Rabobank, social housing

### Content (upload an outline or ppt or something to let us have some sense of what we need).
Outline:
- Universal ledger agent component + background information
- SSI as a service component + background information
- Use case: issues in the Netherlands regarding income tests + issues from social housing corporations and renters
- Demo (not live, will use screenshots and explain)
- Short movie (1 minute)

**Comment by dmitrizagidulin** [comment]
Thanks @dlamers !
